### PR TITLE
Merge main with Noah/use interfaces option

### PR DESCRIPTION
**Pull request by Zetazzz**
Resolved conflicts

set interfaces.useByDefault default value to false. (we usually keep new feature flag default to false and only enable the feature when needed)

changed readme about default values of interfaces.useByDefault

### CODE REVIEW

**Comment by NoahSaso** [comment]
> Resolved conflicts
> 
> set interfaces.useByDefault default value to false. (we usually keep new feature flag default to false and only enable the feature when needed)
> 
> changed readme about default values of interfaces.useByDefault

fwiw, i set `useByDefault` to `true` by default to prevent breaking changes. behavior is only changed when setting the flag to false or setting `useByDefault` to `false`, so it may be a good idea to set the default back to `true`

**Comment by Zetazzz** [comment]
> > Resolved conflicts
> > set interfaces.useByDefault default value to false. (we usually keep new feature flag default to false and only enable the feature when needed)
> > changed readme about default values of interfaces.useByDefault
> 
> fwiw, i set `useByDefault` to `true` by default to prevent breaking changes. behavior is only changed when setting the flag to false or setting `useByDefault` to `false`, so it may be a good idea to set the default back to `true`

Hi

But just like the changes in this PR, only v2 and v3 were changed, which useByDefault was set to true, and others didn't.

I'm not sure there's misunderstanding here?

**Comment by Zetazzz** [comment]
> > > Resolved conflicts
> > > set interfaces.useByDefault default value to false. (we usually keep new feature flag default to false and only enable the feature when needed)
> > > changed readme about default values of interfaces.useByDefault
> > 
> > 
> > fwiw, i set `useByDefault` to `true` by default to prevent breaking changes. behavior is only changed when setting the flag to false or setting `useByDefault` to `false`, so it may be a good idea to set the default back to `true`
> 
> Hi
> 
> But just like the changes in this PR, only v2 and v3 were changed, which useByDefault was set to true, and others didn't.
> 
> I'm not sure there's misunderstanding here?

Ah, I see, I got it now. Ok, then I need to add a flag to make this feature able to turn off for those who don't need this feature.

**Comment by Zetazzz** [comment]
> > Resolved conflicts
> > set interfaces.useByDefault default value to false. (we usually keep new feature flag default to false and only enable the feature when needed)
> > changed readme about default values of interfaces.useByDefault
> 
> fwiw, i set `useByDefault` to `true` by default to prevent breaking changes. behavior is only changed when setting the flag to false or setting `useByDefault` to `false`, so it may be a good idea to set the default back to `true`

Hi, I added a flag in config for this feature and changed back the defaults of those flags you added to true:
https://github.com/cosmology-tech/telescope/pull/520

Please check, Thx!

**Comment by NoahSaso** [comment]
> > > Resolved conflicts
> > > set interfaces.useByDefault default value to false. (we usually keep new feature flag default to false and only enable the feature when needed)
> > > changed readme about default values of interfaces.useByDefault
> > 
> > 
> > fwiw, i set `useByDefault` to `true` by default to prevent breaking changes. behavior is only changed when setting the flag to false or setting `useByDefault` to `false`, so it may be a good idea to set the default back to `true`
> 
> Hi, I added a flag in config for this feature and changed back the defaults of those flags you added to true: #520
> 
> Please check, Thx!

Yes, great! Looks good.

**Pull request merged**
